# Generated by Django 6.0.5 on 2026-07-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employee_annual_ctc_employee_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_exit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
